### ISSUE TITLE
Mali G72

### ISSUE THREAD

**Issue by janrinze** [superna9999/meson_g12a_mali_bifrost#1]
The Kirin 970 has a Mali G72. How much work would it be to add support for the G72?
The G72 is a bifrost GPU too, would there be much overlap or is it a lot different?

**Comment by xlazom00** [comment]
@janrinze it is all about platform integration
look here
https://github.com/superna9999/meson_g12a_mali_bifrost/tree/BX301A01B-SW-99002-r16p0-01rel0_meson-g12a/driver/product/kernel/drivers/gpu/arm/midgard/platform
You will need just kirin integration part. But some integrators like rockchip didn't implement support for kernel modules

**Comment by daedaevibin** [comment]
> The Kirin 970 has a Mali G72. How much work would it be to add support for the G72?
> The G72 is a bifrost GPU too, would there be much overlap or is it a lot different?
> 

If starting off fresh it would need a ton of work. The Mali-G72 cores do not have their own things and rely on the software to work correctly.

**Comment by daedaevibin** [comment]
> @janrinze it is all about platform integration
> look here
> https://github.com/superna9999/meson_g12a_mali_bifrost/tree/BX301A01B-SW-99002-r16p0-01rel0_meson-g12a/driver/product/kernel/drivers/gpu/arm/midgard/platform
> You will need just kirin integration part. But some integrators like rockchip didn't implement support for kernel modules

This is Midgard. Midgard is a separate family of GPU models for ARM.

**Comment by janrinze** [comment]
My Kirin 970 board died long ago. Better to close this issue.

**Comment by daedaevibin** [comment]
> My Kirin 970 board died long ago. Better to close this issue.

Makes sense. Sorry to hear and I hope you've a better system with more support.
